### PR TITLE
Change runtime to python-3.6.3

### PR DESCRIPTION
**Pull request by cclauss**
Tests #226 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Change runtime to python-3.6.3 and test on Heroku

### CODE REVIEW

**Comment by bhaveshAn** [comment]
What is the need ??

**Comment by cclauss** [comment]
readme promises Python 3 compatibility and it unfortunate make claims that our code does not live up to.  An alternate solution would be to edit the readme.

**Comment by vaibhavsingh97** [comment]
@bhaveshAn 
The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020. This decision was made to clarify the status of Python 2.7 and relieve worries for those users who cannot yet migrate to Python 3. See also [PEP 466](https://www.python.org/dev/peps/pep-0466/).

IMO, we should support both Python 2.x and 3.x. What are your opinions?

**Comment by bhaveshAn** [comment]
> IMO, we should support both Python 2.x and 3.x. What are your opinions?

Yes, we are supporting both but at the development phase [check at](https://travis-ci.org/bhaveshAn/query-server/builds/294234727) , and definitely not at deployment phase.
Also, since our heroku deployed application isn't facing any problems on python2 . Is there any need to switch to python3 at this point of time ??

**Comment by cclauss** [comment]
https://pythonclock.org  Supporting Python 3 means the we encourage people to put it into _production_ use.  I think there is broad recognition that our software is not ready for us to make this simple change.

**Pull request closed without merging**
