### PR TITLE
Eliminate the search_without_count method

### LINKED ISSUE #461: Do we need the search_without_count() functions?
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

We have many repetitive functions that I believe could be eliminated.

**Expected behavior:**

Fewer functions required to deliver the equivalent functionality.

**Steps to reproduce:**
Our scrapers have:
* [__def search(self, query, num_results, qtype=''):__](https://github.com/fossasia/query-server/blob/master/app/scrapers/generalized.py#L52) and
* [__def search_without_count(self, query):__](https://github.com/fossasia/query-server/blob/master/app/scrapers/generalized.py#L76)
but perhaps we could remove the second and only have the first.

When we do a __search()__ we are not guaranteeing that we will deliver at least __num_results__ results.  If the upstream search engine only delivers 5 results then we will only return that many even if the caller has set __num_results__ to 10.  If the upstream search engine does not allow us to control how many results we can get then we are not breaking any guarantee if we deliver less than __num_results__.  We are however guaranteeing that we will deliver no more than __num_results__.

So, why not have a default value for the num_results parameter (__def search(self, query, num_results=10, qtype=''):__) and do away with the _without_count_ functions?  Different scrapers could set their default value higher or lower.  The final return could ensure that no more than the requested number of urls are returned with `return urls[:num_results]`

Thoughts?

### PR DESCRIPTION
**Pull request by ankan17**
Fixes #461 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

The functionality of search_without_count has been implemented from the
search method with a default count and the following changes have been
made with regards to tests.

  - Three tests for each scraper has been added to test the search function
    with a popular search term "fossasia"
    + Without any count
    + With a small count(2)
    + With a large count(27)

  - The test_search_without_count method has been removed from the
    test_generalized.py file

### CODE REVIEW

**Comment by bhaveshAn** [comment]
I think you haven't updated the branch.

**Comment by ankan17** [comment]
I last updated when I started working and not after that.. Looks like I have quite a lot of work on my hands now.. More functions to reduce :sweat_smile:

**Comment by ankan17** [comment]
Deployed at https://quiet-sea-69569.herokuapp.com/

**Comment by ankan17** [comment]
@ParthS007 The PR was good yesterday and now it has conflicts -_-

**Comment by ankan17** [comment]
@bhaveshAn The change you requested has been made. The deployment link is provided

**Comment by bhaveshAn** [comment]
Please resolve conflicts

**Comment by vaibhavsingh97** [comment]
@ankan17 Update please

**Comment by ankan17** [comment]
Sorry for the delay.. I will resolve the conflicts ASAP

On 02-Feb-2018 2:28 PM, "Vaibhav Singh" <notifications@github.com> wrote:

@ankan17 <https://github.com/ankan17> Update please

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fossasia/query-server/pull/478#issuecomment-362525770>,
or mute the thread

**Comment by ankan17** [comment]
I am closing this pull request because the git history has diverged and I can't rebase my commits. I will make a fresh PR

**Pull request closed without merging**
