### PR TITLE
[WIP] Fixes #298 Add time analysis of each engine for the results retrieved

### LINKED ISSUE #298: Add time analysis of each engine for the results retrieved
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

time analysis
**Steps to reproduce:**

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #298 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Add time analysis of each engine for the results retrieved

@vaibhavsingh97 @gabru-md Please review the PR. 
Providing heroku deployment at https://hidden-harbor-34393.herokuapp.com/

time

### CODE REVIEW

**Comment by AnshulMalik** [comment]
These changes are include the time taken by the network request from client to server and back.

We should only display the time taken to generate the results, that is returning the time along with results.

**Comment by raju249** [comment]
The changes should be in backend code and not in front end IMHO.
Along with the results include the time and then parse the time to front end.

**Comment by bhaveshAn** [comment]
@AnshulMalik @raju249 @gabru-md The thing is we cannot include time analysis in backend as API `GET /api/v1/search/<search-engine>?query=query&format=format` will get affected and since this api is used by SUSPER and OPEN EVENT to get the responses so can't affect the API.

**Comment by raju249** [comment]
I think we don't have to include or change anything in the URL.
We can send the time in response.
Maybe I am missing something.

**Comment by AnshulMalik** [comment]
@bhaveshAn That's good point.
So let's hold this, and try to think, do we really need this time analysis feature?
If yes, we can discuss with SUSPER or SUSI or others who are using.

**Comment by AnshulMalik** [comment]
@raju249, our response is currently just array, not a dictionary so we can not directly add another key to response.

**Comment by raju249** [comment]
Ohh. 
I thought its a key value pair.
No issues then, I think we can follow what you said.

**Comment by cclauss** [comment]
Scrapers current return one parameter: the urls list.  It would be possible to modify the scrapers to return two parameters instead: the urls list and the elapsed time.  The first parameter would be returned to the calling program and the second parameter would only be used for display, logging, or printing.

**Comment by AnshulMalik** [comment]
That's possible @cclauss, but when I think about it's use case, I don't think this would be useful anywhere?
Why would someone want the time taken to generate the search results ?

**Comment by gabru-md** [comment]
As @AnshulMalik stated. I guess there is no definite benefit/use of actually including the time elapsed into query-server results. I mean i cannot figure out the possible benefits that it will have since it is not a `search engine` 
@bhaveshAn please throw some light on this matter and explain ?

**Comment by AnshulMalik** [comment]
@bhaveshAn remainder

**Comment by cclauss** [comment]
I actually like this PR a lot...  In modern software you should "instrument everything" and round trip time measurement is worth doing as long as at least one user is going to study the resulting data from time to time to understand if we have any bottleneck that are worth addressing.

**Comment by AnshulMalik** [comment]
@cclauss considering round trip time is not recommended, since it can vary a lot depending upon user connection, It won't help anyhow, but marking time for fetching and parsing on backend can be a matrix which we can rely on.

**Comment by cclauss** [comment]
Our code's performance is roughly the time to run [server.search()](https://github.com/fossasia/query-server/blob/master/app/server.py#L41) - the time to run [each scraper's search()](https://github.com/fossasia/query-server/blob/master/app/scrapers/__init__.py#L46-L48).  Once we have tuned the former, we can focus on which search engines are too slow.  My bet would be that some are faster than others but without metrics, we do not know for sure.

**Comment by raju249** [comment]
I think unless we pass the time in response from server, adding time via `js ` is not useful.

**Comment by cclauss** [comment]
There are two things: What we want to measure #382 and how we want to measure it (this PR / discussion).  I believe the “what” should come before the “how”.  Is it possible for the maintainers to respond to #382 so we know what we are trying to do before we decide how we are going to do it?

**Comment by mariobehling** [comment]
What is the status of this? Should this be closed and reopened later, when there is a follow-up?

**Comment by bhaveshAn** [comment]
@mariobehling I think we should go with adding this feature, since time analysis comes under performance category. And thats cool idea.
Though the discussion is only on whether we should implement it 
1. In Flask backend where the API `GET /api/v1/search/<search-engine>?query=query&format=format` will get affected and we will return the search results response alongwith time taken.
2. In JavaScript frontend where we just calculate the time difference between the clicking the submit button and the response returned by backend. ( AS DONE IN THIS PR )
Please give your opinion.

**Comment by mariobehling** [comment]
@vaibhavsingh97 What are your thoughts?

**Comment by vaibhavsingh97** [comment]
@mariobehling @bhaveshAn IMO, instead of checking time on client side, we should add one time parameter to the backend API and return the response along with the time. But my question is where time will be useful?

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Update please

**Comment by bhaveshAn** [comment]
> In Flask backend where the API GET /api/v1/search/<search-engine>?query=query&format=format will get affected and we will return the search results response alongwith time taken.

@vaibhavsingh97 Should I make these corresponding changes.

**Comment by vaibhavsingh97** [comment]
@bhaveshAn yes, just pass one `dictionary` context while rendering the page

**Comment by bhaveshAn** [comment]
This PR needs updation in codebase. Please give some time.

**Comment by mariobehling** [comment]
I agree time should be retrieved from the server, not the client. 

Work on this issue is stalled. Closing this due to inactivity. Please reopen new PR if you want to resolve this.

**Pull request closed without merging**
