### PR TITLE
Fixes #410: Changes buttons to dropdown

### LINKED ISSUE #410: Replacing Buttons with Dropdown
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently we have buttons for all separate scrappers
**Expected behavior:**

It is a bit untidy and so I suggest adding a dropdown with all the scrappers to choose from.

**Would you like to work on it**
Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by abishekvashok**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
Changed multiple server listing buttons into a single dropdown to
enhance accessiblity of the UI.

Fixes #410

#### Preview
screenshot_20171229_212513

### CODE REVIEW

**Comment by gabru-md** [comment]
@abishekvashok Rather than having simple drop down, I was aiming for something more like a drop down that contains elements the same as the buttons.
I believe it is easy for you. Can you try doing it as well ?

**Comment by abishekvashok** [comment]
A drop down with icons maybe?

**Comment by gabru-md** [comment]
Yes ! Like having the same buttons in the drop down. Because the buttons kind-of look good. :)

**Comment by abishekvashok** [comment]
@gabru-md i don't know if it will look good adding that buttons itself as drop down. But I may be wrong. Anyway, let's try both.

**Comment by gabru-md** [comment]
Just Provide with a screenshot and if it does not look good we will revert back to your changes :+1: 
I hope it is fine ?

**Comment by abishekvashok** [comment]
@gabru-md sure.

**Comment by abishekvashok** [comment]
@gabru-md I am trying die hard to style it, but bootstrap although included does not seem to work properly, it is not displaying icons nor letting me add dropdowns

**Comment by vaibhavsingh97** [comment]
@abishekvashok https://codepen.io/fsanggang/pen/ZOepzE This may help you

**Comment by abishekvashok** [comment]
@gabru-md @vaibhavsingh97 please squash and merge.

screenshot_20171229_212513

**Comment by vaibhavsingh97** [comment]
@abishekvashok Can we have Engine dropdown, Max drop down and submit in 1 Row. Also, can you please share deployment link for this PR.

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
@vaibhavsingh97 done.
screenshot_20171231_185422

@fossasia/query-server-searss-admin please review

**Comment by abishekvashok** [comment]
Please do a squash and merge s I have resolved conflicts :)

**Comment by abishekvashok** [comment]
Ping @vaibhavsingh97

**Comment by abishekvashok** [comment]
On the way

**Comment by abishekvashok** [comment]
@ParthS007 @vaibhavsingh97 @gabru-md here's a live link: https://secret-anchorage-61504.herokuapp.com/

**Comment by abishekvashok** [comment]
@vaibhavsingh97 it has merge conflict resolution commits, that's why I did'nt squash

**Comment by abishekvashok** [comment]
@vaibhavsingh97 at last learned how to squash while resolving conflicts :) `git` is awesome. Rewritten history.

**Comment by vaibhavsingh97** [comment]
Please update your branch and change your commit message to something relevant

**Comment by abishekvashok** [comment]
@vaibhavsingh97 ar you still seeing conflicts?

**Comment by vaibhavsingh97** [comment]
@abishekvashok I can see the `update branch` option so yes

**Comment by abishekvashok** [comment]
@vaibhavsingh97 so I see we can't do a history update, i.e, can we have more than one commit. Can you do a squash and merge. Please clear your review so that I can update the branch from web.

**Comment by AnshulMalik** [comment]
I suggest gitter for chat

**Comment by abishekvashok** [comment]
@AnshulMalik sorry, but a reload made me see this:

screenshot_20180101_204536

I guess you would be updating the history of the repository after pushing this PR.

**Comment by AnshulMalik** [comment]
I didn't get it @abishekvashok, I'll still try to answer, I don't have access for merge here, I just drop by here once in a while. 

I was getting a lot of emails, so I came to check out what's going on.

**Comment by abishekvashok** [comment]
@AnshulMalik I am sorry but it's intresting that instead of the merge we have update branch here without conflicts.
After a research here's a conclusion:

> It's same as squash and merge

Meaning there's gonna be a history update which is true in case of a squash and merge.

**Comment by vaibhavsingh97** [comment]
Good work @abishekvashok 👍

**Comment by abishekvashok** [comment]
Thanks @vaibhavsingh97 @ParthS007 

Link to my task: https://codein.withgoogle.com/dashboard/task-instances/6573865834643456/

**Pull request merged**
