### PR TITLE
Added Mojeek support

### LINKED ISSUE #295: Add Mojeek support
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add support for a UK based search engine [Mojeek](https://www.mojeek.co.uk/)
**Steps to reproduce:**

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #295 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Mojeek support (A UK based search engine)

@gabru-md @vaibhavsingh97 @shashank-sharma Please review. 
Providing the heroku deployment at https://intense-plateau-86110.herokuapp.com/
Thanks !!

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Do we really need these?

**Comment by bhaveshAn** [comment]
Any search engine which is not a meta search engine or which doesn't depends on some other search engine for getting the results can be added in this project.

**Comment by gabru-md** [comment]
@bhaveshAn I definitely agree with @vaibhavsingh97 .
Do we really need so many of these ? 
@mariobehling can you please comment on this ? So that we can know

**Comment by bhaveshAn** [comment]
@mariobehling @niranjan94 Please review

**Pull request closed without merging**
