### PR TITLE
Reformatted Code in more python fashion

### LINKED ISSUE #396: Reformat Code in more python format
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #396 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Reformatted Structure
* Added looping construct in template code
* Renamed variables accoeding to python convention

### CODE REVIEW

**Comment by ParthS007** [comment]
@yashLadha Please resolve Travis and add proper PR message.

**Comment by yashLadha** [comment]
Done @ParthS007

**Comment by yashLadha** [comment]
One click heroku deplyment asks me for verification. But when i go for the verification it asks me for the card information @ParthS007

**Comment by bhaveshAn** [comment]
Try using `docs/installation/heroku.md` guide

**Comment by yashLadha** [comment]
https://quiet-shore-17572.herokuapp.com/

**Comment by yashLadha** [comment]
image

**Comment by yashLadha** [comment]
Update your review @ParthS007

**Comment by ParthS007** [comment]
@yashLadha First Please update the PR name

**Comment by yashLadha** [comment]
@ParthS007 is this fine.

**Comment by yashLadha** [comment]
Sure @vaibhavsingh97

**Comment by yashLadha** [comment]
Give me a minute

**Comment by yashLadha** [comment]
Done @vaibhavsingh97  :+1:

**Pull request merged**
