### PR TITLE
Fix bootstrap column spacing. Fixes #406

### LINKED ISSUE #406: Quer-server doesn't seem to work on a smaller window
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Query server doesnt seem to work when the window size is resized to a smaller one.

**Expected behavior:**

Query server works when the window size is resized to a smaller one.

**Steps to reproduce:**
Resize the window size to a smaller one.

Representation: 
fossasia

### PR DESCRIPTION
**Pull request by dgarvit**
Fixes #406 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Add the right bootstrap column so that query server works even when window is resized

### CODE REVIEW

**Comment by dgarvit** [comment]
Running at http://query-server-patch.herokuapp.com/

**Comment by dgarvit** [comment]
peek 2017-12-29 14-22

**Comment by gabru-md** [comment]
Please follow best practices and rename your PR to `Fixes #issue` and followed by the message.
Thanks!

**Comment by dgarvit** [comment]
@gabru-md I made the respective changes! :smile:

**Pull request merged**
