### PR TITLE
Fixes#442 Removes Hound as flake8 + codacy + codecov + pytest are sufficient

### LINKED ISSUE #442: Remove Hound
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Presently, Hound CI doesn't make comments.

**Expected behavior:**
Removes Hound as flake8 + codacy + codecov + pytest are sufficient for testing code quality.

I am working on this Issue.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #442 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Removes Hound as flake8 + codacy + codecov + pytest are sufficient.

### CODE REVIEW

**Comment by ParthS007** [comment]
@cclauss @vaibhavsingh97 @bhaveshAn Please review. Thanks

**Comment by ParthS007** [comment]
@cclauss  I am just finding way to run hound ci bot , I will revert the changes

**Comment by ParthS007** [comment]
@cclauss  I am thinking of adding pyflakes instead of hound ci, your views?

**Comment by cclauss** [comment]
Flake8 does both PyFlakes plus PEP8  (thus the name) plus McCabe complexity analysis.  Adding PyFlakes would be redundant.

We should just kill the hound.  It serves no purpose  (even when it is working -- which it is not).

I think flake8 + codacy + codecov + pytest are sufficient for our purposes.

**Comment by ParthS007** [comment]
ok @cclauss  removing hound 👍

**Comment by ParthS007** [comment]
@cclauss  Now review please .Thanks for review 👍

**Comment by vaibhavsingh97** [comment]
@cclauss We added Hound CI to help beginners as Hound CI comments the violations with Line Number. Also, beginner don't know much about codacy,  flake8, etc. So IMO, we shouldn't remove Hound CI.

**Comment by ParthS007** [comment]
@vaibhavsingh97  Hound is not active for so long and it is not giving messages for error if they are present even after proper configuration and as said by @cclauss flake8 + codacy + codecov + pytest is enough for code quality and now we have unitests too. your say @vaibhavsingh97 @bhaveshAn ?

**Comment by ParthS007** [comment]
I will close the PR if majority says to retain Hound , no issues in that :)

**Comment by vaibhavsingh97** [comment]
@ParthS007 Hound CI needs activation by admin of Repo and it's not activated by admin

**Comment by ParthS007** [comment]
**I will not be able to squash commits as I have updated the branch**

**Pull request merged**
