### PR TITLE
Add CSV support

### LINKED ISSUE #210: Addition of  CSV support
- [x] Feature Request

#### Current Behaviour
As of now, result supports only JSON, XML.

#### Expected Behaviour
Result should support JSN, XML, CSV 

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by dgarvit**
Fixes #210 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Add support for result to be returned in CSV format

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@dgarvit Please share live deploy link

**Comment by vaibhavsingh97** [comment]
@dgarvit Link not working
image

**Comment by dgarvit** [comment]
@vaibhavsingh97 the error was caused because someone ran the Yandex search. i request you not to use it for now (probably disable it since it is not working and requires the program to be killed). I restarted the service. I request you to review it now :)

**Comment by gabru-md** [comment]
@bhaveshAn from next time please wait for atleast 2 reviews before merging  :)

**Comment by ParthS007** [comment]
Agreed with @gabru-md  👍

**Comment by bhaveshAn** [comment]
Sure @gabru-md @ParthS007

**Pull request merged**
