### PR TITLE
Added search engine name to print parsed output #301

### LINKED ISSUE #301: Add search engine name to the printed parsed output
@starlord1311 Would you be interested to work on this one?

**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Current printed output is usually __parsed[{“title”: ...__
**Expected behavior:**

Desired printed output could be __Google parsed: [{“title”: ...__

**Steps to reproduce:**
* Run a Quora search to see the right kind of output.
* Run a Google search to see the wrong kind of output.

https://github.com/fossasia/query-server/blob/master/app/scrapers/quora.py#L21
Does it right and the other search engines should be modified to do things the same way.
https://github.com/fossasia/query-server/blob/master/app/scrapers/google.py#L27

This change would make it easier to find and fix bugs like #271

### PR DESCRIPTION
**Pull request by starlord1311**
Fixes #301 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-The print parsed output shows "Google parsed:..." instread of "parsed..."

-done for all the search engines. attaching changes made in google code as an example
screenshot 9

### CODE REVIEW

**Comment by starlord1311** [comment]
@cclauss i made the required changes in the latest commit. please check
screenshot 10

**Comment by gabru-md** [comment]
@starlord1311 please squash your commits into one.

**Comment by cclauss** [comment]
A colon and a __space__ like json output.

**Comment by starlord1311** [comment]
after adding the print line to the ask.py file the pull request shows this. can someone tell where am i going wrong with the ask.py file?

**Comment by cclauss** [comment]
@starlord1311 Both testers (Travis and Codacy) are complaining because there is a whitespace to the right of the print() function call.  Deleting that whitespace so that __)__ is the last character on the line will silence them.  You can see their diagnosis by clicking __Details__ above to the right of each tester.

**Comment by rupav** [comment]
@starlord1311 please squash your commits into 1 :)

**Comment by mariobehling** [comment]
Thanks! Please squash your commits next time. Keep it up!

**Pull request merged**
