### PR TITLE
Fixes #357 Add Mojeek in README

### LINKED ISSUE #357: Add Mojeek in README
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently Mojeek is not written in
> The query server can be used to search a keyword/phrase on a search engine (Google, Yahoo, Bing, Ask, DuckDuckGo, Yandex, Baidu, Exalead, Quora, Parsijoo and Youtube) and get the results as json or xml. The tool also stores the searched query string in a MongoDB database for analytical purposes.
**Expected behavior:**

**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #357 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Mojeek in README

@vaibhavsingh97 @gabru-md @mariobehling Please review !! 
Thanks !!

### CODE REVIEW

**Comment by cclauss** [comment]
Please resolve conflicts

**Comment by raju249** [comment]
@bhaveshAn Please resolve conflicts so that we can merge this PR.

**Comment by ParthS007** [comment]
@bhaveshAn This is not the kind the issue that you should resolve.We have GCI going on and students can solve it but anyways Please resolve conflicts and I will merge it.

**Comment by cclauss** [comment]
Please also add Dailymotion

**Comment by bhaveshAn** [comment]
@ParthS007 
> This is not the kind the issue that you should resolve.We have GCI going on and students can solve it

Sure will keep in mind.
Updated and resolved the conflicts in the PR. Please merge

**Pull request merged**
