### PR TITLE
Fixes #472 #474 #476 Add News search in Baidu, Parsijoo & Mojeek

### LINKED ISSUE #472: Add News search support for Mojeek
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, no support for News search in Mojeek.
**Expected behavior:**

Adding News search support for Mojeek
**Steps to reproduce:**

**Yes, wanna work on this issue**

### LINKED ISSUE #474: Add News search support for Parsijoo
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, no support of news search for Parsijoo.
**Expected behavior:**

Add News search support for Parsijoo.
**Steps to reproduce:**

**Yes, wanna work on this issue**

### LINKED ISSUE #476: Add News search support for Baidu
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently, no support for news search in Baidu.
**Expected behavior:**

Adding news search support in Baidu.
**Steps to reproduce:**

**Yes, wanna work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #472 
Fixes #474 
Fixes #476 
Addresses #468 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added News search in Baidu, Parsijoo & Mojeek
- Added tests for the same.

Providing Heroku deployment at https://young-dusk-37307.herokuapp.com/
@shankybora @rohitsainicool @gabru-md Please review. Thanks !!

### CODE REVIEW

**Comment by ParthS007** [comment]
@rohitsainicool  @shankybora  Please don't review without contributing and knowing about a project . You are welcome to contribute to FOSSASIA 👍

**Comment by bhaveshAn** [comment]
Approval by a maintainer hence merging.

**Comment by mariobehling** [comment]
Please dont merge your own PRs.

**Comment by ParthS007** [comment]
@mariobehling  I and @vaibhavsingh97  have already asked him for to follow best practices. We cannot rely on reviewers that are actually not contributing to project and @rohitsainicool  & @shankybora  are even new to Github.

**Comment by bhaveshAn** [comment]
Okay @mariobehling @ParthS007

**Pull request merged**
