### PR TITLE
[Imp] Added Ask.com search engine support

### PR DESCRIPTION
**Pull request by ksubbu199**
Added Ask.com search engine support

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@ksubbu199 good to see you on board immediately after the event, continue the enthusiasm in you. please look at this blog http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ and follow those practices. 
Create an issue and reference the issue number on pull request.
If you need help, you can ping us on gitter channel at http://gitter.im/fossasia/query-server

**Comment by niranjan94** [comment]
@ksubbu199 why are there two PRs open for the same (#122) ?

**Comment by Pk13055** [comment]
@niranjan94 What is wrong with this PR?

**Comment by gabru-md** [comment]
There are some files which are conflicting with your fork.
Kindly resolve them and proceed.
:D

**Comment by Pk13055** [comment]
Sounds good.

**Comment by Pk13055** [comment]
@ksubbu199 This issue is outdated as of #148, please close it.

**Pull request closed without merging**
