### PR TITLE
syntax highlighting for json response #52

### PR DESCRIPTION
**Pull request by starlord1311**
Fixes #299 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-made changes in the index.html for syntax highlighting
-

### CODE REVIEW

**Comment by ParthS007** [comment]
@starlord1311 please add a screenshot of the changes

**Comment by starlord1311** [comment]
@ParthS007  ss of the changes i made in the code right?

**Comment by starlord1311** [comment]
sorry didnt get your question prperly @ParthS007

**Comment by ParthS007** [comment]
I mean to say that  after doing changes , take the screenshot which shows changes  done by you

**Comment by starlord1311** [comment]
screenshot 8

**Comment by vaibhavsingh97** [comment]
@starlord1311 After you made changes, We want you to run locally and see the changes made by is the expected output. If yes, then took screenshot and while making a PR add screenshot 👍

**Comment by niranjan94** [comment]
@starlord1311 also provide a test deployment on heroku please. We need to make it a point to do this for all PRs.

**Comment by vaibhavsingh97** [comment]
@niranjan94 What about automatic heroku deployment with each PR?

**Comment by niranjan94** [comment]
Heroku pipeline (which can be used for auto deployments) works properly only if all branches exist on this repository itself. Not when the branches are from cloned repos. 

And its not hard for contributors to do a heroku deployment. So, its upto the contributors to provide deployments for each PR.

**Comment by starlord1311** [comment]
@vaibhavsingh97 how to run it locally?

**Comment by starlord1311** [comment]
screenshot 11
this is what is coming when i open the index.html

**Comment by bhaveshAn** [comment]
@starlord1311 Please go through the Local installation of this project. And then run it `python app/server.py`

**Comment by bhaveshAn** [comment]
Any update ??

**Comment by starlord1311** [comment]
@bhaveshAn i am still not able to run it loally idk why

**Comment by bhaveshAn** [comment]
Then how are you making the PRs ??
Please don't make untested PRs.

> i am still not able to run it loally idk why

goto `http://localhost:7001/` and tell the status ??

**Comment by starlord1311** [comment]
screenshot 19

**Comment by starlord1311** [comment]
is this fine?

**Comment by starlord1311** [comment]
@bhaveshAn ^

**Comment by vaibhavsingh97** [comment]
@starlord1311 Can you please post the screenshot of the output.

**Comment by starlord1311** [comment]
screenshot 22

**Comment by starlord1311** [comment]
@vaibhavsingh97 pic of the output

**Comment by mariobehling** [comment]
Ok, thanks.

**Comment by AnshulMalik** [comment]
@mariobehling No one approved this PR

**Pull request merged**
