### PR TITLE
Disable yandex on frontend

### LINKED ISSUE #407: Disable Yandex for now
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

In reference to #387.

I'd like to work upon this once maintainers confirm it.

### PR DESCRIPTION
**Pull request by dgarvit**
Fixes #407 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Disabled yandex search on frontend, since it is not working for now.

### CODE REVIEW

**Comment by dgarvit** [comment]
yandex

**Comment by vaibhavsingh97** [comment]
@dgarvit If you had disabled it than please give user feedback that it's disabled temporary

**Comment by dgarvit** [comment]
@vaibhavsingh97 where should it be given? I mean, write it on page or a popover?

**Comment by dgarvit** [comment]
screenshot from 2017-12-29 19-27-09

@vaibhavsingh97 is this okay?

**Comment by bhaveshAn** [comment]
@dgarvit Is this feedback `Yandex has been temporarily disabled` coming when we hover on Yandex button ?

**Comment by dgarvit** [comment]
@bhaveshAn yes

**Comment by dgarvit** [comment]
Running here: http://query-server-patch.herokuapp.com/

**Comment by vaibhavsingh97** [comment]
@dgarvit when user click on than invoke that popover

**Comment by dgarvit** [comment]
@vaibhavsingh97 the button is disabled so... it cant be clicked. And from UI point of view I'd prefer hover than click. Your views? @bhaveshAn @vaibhavsingh97

**Pull request merged**
