### PR TITLE
Fixed: Internal server while querying with Google

### LINKED ISSUE #166: Showing Internal Server Error when tried to search on Query Server
Query Server responded with 500 Internal Server Error
Update: Error showing only when searching using Google

screenshot from 2017-09-23 02-41-14

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #166 
**Screenshot after fix:**
image

@gabru-md @nikhilrayaprolu Please review

### CODE REVIEW

**Comment by gabru-md** [comment]
I donot have merging authority here.
@nikhilrayaprolu this looks good. I suggest you to merge it. Rest is upto you.
Cheers.

**Comment by vaibhavsingh97** [comment]
@gabru-md I just asked for review 😄

**Comment by shashank-sharma** [comment]
Hi, I have already sent PR with exact same code earlier ? Why doing this again ? https://github.com/fossasia/query-server/pull/169

**Comment by vaibhavsingh97** [comment]
@shashank-sharma Sorry, I havn't seen. Should i close this?

**Comment by shashank-sharma** [comment]
@vaibhavsingh97 I don't know you should have seen this earlier. By the way how come you have the exact same code as mine ? Kind of strange, coincidence ?

**Comment by vaibhavsingh97** [comment]
@shashank-sharma It's a conincidence as i tried many ways and this code fixed it 😅

**Comment by shashank-sharma** [comment]
But then again there is no point to open this merge because already I have updated it and sent PR.

**Comment by vaibhavsingh97** [comment]
@shashank-sharma I am closing this as You already fix this issue. 😄

**Pull request closed without merging**
