### PR TITLE
Fix margin of Engine label and dropdown

### LINKED ISSUE #483: Small UI bug in mobile view
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
A small bug in UI can be seen when choosing 'duckduckgo' or 'dailymotion' while in mobile view as below. Also, the padding of the dropdown and it's label i.e. `Engine:` is not correct as it is touching the boundary.

image

image

**Expected behavior:**
UI should be elegant and responsive.

**Steps to reproduce:**
Simply visit the [original](http://query-server.herokuapp.com/] website on the smartphone or on the desktop using developer's tool to get a simulated mobile view to reproduce the bug.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #483 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Margin set for correct indent in mobile device too.
- Try this on mobile device: https://cryptic-hamlet-20959.herokuapp.com/
- Original link: https://query-server.herokuapp.com/

img-20180129-wa0002

### CODE REVIEW

**Comment by rupav** [comment]
@realslimshanky please review.

**Comment by realslimshanky** [comment]
The two labels 'engine' and 'type' don't align to one another. It'll look way better if they start from the same margin to left.

**Comment by rupav** [comment]
@realslimshanky updated
screenshot_20180129-220011
Now between dropdown and Label there is margin of 2 px too.

**Comment by realslimshanky** [comment]
Nice work. Can we also get the margin reduced between 'Type' and 'General' so they look like they belong together? Also some space between drop-down menu containing search engine names and 'Type' label.

**Comment by rupav** [comment]
@realslimshanky, yes its needed, otherwise not looking good, so I am removing the padding-top of `General` and images and video.

**Comment by rupav** [comment]
I think it looks good now, your opinion @realslimshanky ?
changes

**Comment by rupav** [comment]
@realslimshanky done, can you please squash while merging, I am having conflicts while squashing last 2 commits.

**Comment by realslimshanky** [comment]
@rupav you cannot merge last two of the commits in this PR as they are not historically adjacent.

**Comment by rupav** [comment]
@realslimshanky what does it mean "historically adjacent" ? So what should I do now ?

**Comment by realslimshanky** [comment]
@rupav continuous. You don't need to worry about this, it can be merged when approved.

**Comment by rupav** [comment]
@ParthS007 no I can't , see above discussion. Not historically adjacent commits

**Comment by rupav** [comment]
@realslimshanky resolved. Can it be please merged now, got 3 approvals?

**Pull request merged**
