### PR TITLE
529 mock issue

### LINKED ISSUE #529: Using enter to display a query
**I'm submitting a ...**
- feature request

**Current behavior:**
When we type any text in the search box and press enter nothing happens.

**Expected behavior:**
After we type any text in the search box and press enter a search result with by default JSON format should be displayed.

**Steps to reproduce:**
Add a jquery keypress event to submit the form when enter key is pressed.

### PR DESCRIPTION
**Pull request by rohitjain00**
Fixes #529

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added search for query on pressing enter.
- By default JSON format is displayed but we can select any other type if we want and then press enter.

### CODE REVIEW

**Comment by rohitjain00** [comment]
Should I remove the Submit button as well?

**Comment by vkartik97** [comment]
Hey @rohitjain00 
It looks good!
Also, if you are trying to solve #516 (Removing Submit Button)with this PR, Please update your fork branch with `fossasia/query-server` as the UI was changed in PR #527 and your branch is not up to date with it.
Cheers!

**Comment by rohitjain00** [comment]
I'll add another PR with Removing submit button and change UI in accordance with #527

**Comment by mariobehling** [comment]
The linked issue is closed already.

**Pull request closed without merging**
