### PR TITLE
Increase number of results to 100 #59

### PR DESCRIPTION
**Pull request by fazeem84**
Updated google_search and overloaded the get_google_page function by
introducing Start Index Parameter,the start index is sent to Google URL
as http request parameter(This involves 10 http calls to google to fetch
100 result)

### CODE REVIEW

**Comment by fazeem84** [comment]
Dont know how todo CI for this so sending for review

**Comment by enigmaeth** [comment]
@fazeem84 Please go through [best practices](http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) and edit PR description( Don't forget to add Fixex #<issue-number> in description).

**Comment by mariobehling** [comment]
I am merging this.

@fazeem84 Please follow best practices for future contributions. It helps to keep all developers aligned. Thank you!

http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by fazeem84** [comment]
Thanks Mario..
Next Time onward I will follow the best Practices

**Pull request merged**
