### PR TITLE
Reestablish compliance with PEP8

### PR DESCRIPTION
**Pull request by cclauss**
Fixes PEP8 compliance -- A simple change that removes a long line and removes a backslash which are both non-compliant with PEP8.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- http://pep8.org/#maximum-line-length

### CODE REVIEW

**Comment by cclauss** [comment]
Hi @realslimshanky It can be quite repetitive to keep re-basing each time someone merges a PR so for small changes (this change is a one liner) the trend seems to be to re-base only once there are enough positive reviews to cause a merge.

**Comment by cclauss** [comment]
@bhaveshAn Done.  Good catch.  Those lists repeated twice was just an accident waiting to happen.  I made them tuples which have two advantages: 1. They are smaller in memory and 2. nobody can change them at runtime.

**Comment by vaibhavsingh97** [comment]
@bhaveshAn This PR is ready to merge 🚀 
Please approve and merge. thanks

**Comment by vaibhavsingh97** [comment]
Thanks @bhaveshAn 👍

**Pull request merged**
