### PR TITLE
Make our code compliant with PEP8

### PR DESCRIPTION
**Pull request by cclauss**
Fixes [PEP8 compliance](https://www.python.org/dev/peps/pep-0008/)

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Remove artificial max-line-length from __.travis.yml__
- Fix ask.py to not violate PEP8

### CODE REVIEW

**Comment by realslimshanky** [comment]
Please mention the issue with which this PR is related.

**Comment by cclauss** [comment]
I have done so in the initial comment above.  PEP8 is an approved Python Enhancement Proposal for the formatting of Python code to improve readability.

**Comment by cclauss** [comment]
To keep us PEP8 compliant on all future PRs.  The 85 was artificial and not aligned with PEP8.

**Comment by cclauss** [comment]
Can I please get your reviews?

**Pull request merged**
