### PR TITLE
Added Indeed Search

### LINKED ISSUE #433: Add Indeed Search
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no feature to search using Indeed.

**Expected behavior:**
There should be a feature for the same.

### PR DESCRIPTION
**Pull request by Remorax**
Fixes #433 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Indeed Search

#### Screenshots:

screen shot 2018-01-11 at 1 40 29 am
screen shot 2018-01-11 at 1 40 48 am

### CODE REVIEW

**Comment by cclauss** [comment]
I though we had a moratorium on adding random search engines.
* https://github.com/fossasia/query-server/pull/373#issuecomment-350497499
* https://github.com/fossasia/query-server/pull/362#issuecomment-350497610
* https://github.com/fossasia/query-server/pull/360#issuecomment-350497636
* https://github.com/fossasia/query-server/pull/359#issuecomment-350837089

**Comment by Remorax** [comment]
Okay, I just wanted to raise a couple of points.
1. I'm new to this repo, and I was unaware of the moratorium
2. This is not a "random" search engine like majeek or yandex. Indeed is a very standard website used for job search, which hasn't been done so far. I agree adding more search engines isn't necessary, but adding Search engines which give specialised results like Indeed, Dailymotion or Quora should be beneficial imo, because these are sites People use on a daily basis.
Let the others pitch in, and if the consensus is that this should be closed, I'll close it myself, that's not a problem :smile:

**Comment by Remorax** [comment]
The URL on which I've deployed: https://radiant-plains-64367.herokuapp.com/

**Comment by dgarvit** [comment]
Agreed with @cclauss. Lets focus on making it more stable rather than adding more search engines. I think they are enough for now :smile:

**Comment by ParthS007** [comment]
Closing this PR as no more search engine is required and also on approval from @cclauss @dgarvit

**Pull request closed without merging**
