### PR TITLE
Added Quora support

### LINKED ISSUE #286: Add Quora support
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #286 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Since few search engines are there which shows all the results on there first page, hence we doesn't require any page index and codebase added for such search engines support too. Example: Quora
- Added Quora support
@gabru-md @cclauss @mariobehling please review.
Providing the heroku deployment for this PR at https://safe-falls-51968.herokuapp.com/ 
Thanks !!

### CODE REVIEW

**Comment by gabru-md** [comment]
@bhaveshAn Why is Quora not producing more than 10 results?
Can you please let us know so that maybe we could help.

**Comment by bhaveshAn** [comment]
@gabru-md please visit https://www.quora.com/search?q=fossasia
Here, you will find that unlike other search engines there are few ones that doesn't support page index that we used in google, bing, etc.
There are search engines like Quora that shows all the results in the first page only, so definitely all 100 results can't be fetched because isn't necessary that each time we could find 100 results for a particular keyword on quora search on a keyword.

**Comment by gabru-md** [comment]
Thank You @bhaveshAn . It is a genuine reason and Thanks a lot for your contribution to query-server.
@mariobehling @AnshulMalik Please Review and see if it can be merged.

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
