### PR TITLE
Added Twitter search

### LINKED ISSUE #420: Add Twitter search
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There's no feature to search tweets.

**Expected behavior:**
There should be a feature to search tweets

I would like to work on this 😄

### PR DESCRIPTION
**Pull request by Remorax**
Fixes #420 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Twitter search by making a request to the Loklak API

@ParthS007 @vaibhavsingh97  Please review :)

  
screen shot 2018-01-06 at 10 21 03 pm
screen shot 2018-01-06 at 10 21 23 pm

### CODE REVIEW

**Comment by Remorax** [comment]
@ParthS007 I'm unable to deploy it, I'm getting the same error I was getting earlier. Could you check the screenshots or pull my branch. Thanks 😄

**Comment by Remorax** [comment]
This is the URL I've deployed it to, it gives an application error for me when I open it: https://git.heroku.com/stormy-thicket-73131.git

**Comment by Remorax** [comment]
I'm getting an internal server error after deploying it. Works perfectly fine on localhost, though.

screen shot 2018-01-15 at 3 33 15 am
screen shot 2018-01-15 at 3 33 22 am

Any suggestions? @vaibhavsingh97 @ParthS007

**Comment by Remorax** [comment]
@ParthS007 This is the deployment link: https://frozen-headland-42995.herokuapp.com/ but like I said and like I showed in the screenshot, it gives an internal server error but it works on localhost. Any ideas what could be causing the problem, and how I should resolve it?

**Comment by Remorax** [comment]
@bhaveshAn I'm pretty sure this doesn't "harm" the main heroku deployment 😆 .  All the other search engines work perfectly and this would too. Just try it out on localhost it works perfectly.
As for other the necessity of other search engines, I believe we've already been through this countless times, and I could repeat what I said and you could raise this again after a couple of days, but I started this issue after the approval of people in the gitter channel, and since this does not cause any "harm" to the website, and since this is a feature everyone agreed was necessary, I really don't see why my effort should be wasted as well.
However, if you have any solutions for this bug, please let me know.

**Comment by gabru-md** [comment]
@vaibhavsingh97 @ParthS007 do we even need a twitter search ? 
I mean we already have loklak for the actual and very same purpose. It tracks and stores tweets for the same. 
I mean I do not get the whole point of twitter search. Mind if you guys can enlighten me on this ?

**Comment by mariobehling** [comment]
I think this is ok to add. Looks like a good job. Please get the approval of everyone. Cheers.

**Comment by Remorax** [comment]
Thank you @mariobehling. Sure, I will 😄 
@bhaveshAn, This is not something that by its nature won't work on heroku. Me and @vaibhavsingh97 are debugging this, and I'm not asking for this to be merged without it being fixed 👍

**Comment by bhaveshAn** [comment]
Great @Remorax Nice spirit :+1:

**Comment by Remorax** [comment]
@ParthS007 Its mainly because of the fact that I've added a search method for Twitter, and that's why its decreasing. Can this be ignored?
screen shot 2018-01-23 at 12 38 33 am

**Comment by Remorax** [comment]
@mariobehling @ParthS007 
The commits are commits for updating the branch made using the GUI and so I'm unable to squash them 😅 . Can the latest commit be merged?
And so many PRs have been merged since I made this PR that I'm having to update my branch again and again 😅 . Its been 16 days since I made this, and so can this be merged immediately? Thank you 😄

**Comment by bhaveshAn** [comment]
Hey @Remorax Please add tests, I think you forgot that every feature based PR now needs a test to run.

**Comment by Remorax** [comment]
What kind of tests should I be adding here @bhaveshAn? I've not scraped a website and its an API call that returns a different set of tweets every time I make the call, even for the same keyword so what should I test 😅 ? I don't think its required here because the API works perfectly and I'm just making a call to it.

**Pull request merged**
