### PR TITLE
Fixes #305 Adds Medium Support

### LINKED ISSUE #305: Add Medium support
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:*

**Steps to reproduce:**

Yes, I would like to work on this issue

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #305 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Now query server also has medium support
- Please find [ heroku deployment](https://glacial-eyrie-31155.herokuapp.com/) here

### CODE REVIEW

**Comment by ParthS007** [comment]
@bhaveshAn I have updated Heroku deployment link in PR message.

**Comment by ParthS007** [comment]
@bhaveshAn  by mistake my repo was deleted and now I am unable to squash commits. Can you please squash and merge this PR while merging.thanks

**Comment by ParthS007** [comment]
@bhaveshAn  @cclauss @mariobehling  Please review

**Comment by ParthS007** [comment]
Thanks, @bhaveshAn  for approving. I will keep this in mind from next PR

**Comment by mariobehling** [comment]
Please refer to comment in issue. Cheers.

**Pull request closed without merging**
