### PR TITLE
Implement absolute_import in Scrapers w/ tests

### LINKED ISSUE #226: Scrapers should implement absolute_import
The current scrapers will not work on Python 3 because they do relative importing.  The problem is shown here: https://travis-ci.org/fossasia/query-server/jobs/282968780#L558

The solution is to:
1. from __future__ import absolute_import
2. from .generalized import Scraper  # add the dot (.)
(See https://github.com/fossasia/query-server/pull/225/files#diff-ae74241666286cc647595b08d2de8ac2 for an example)

Without item 2 above, Python 3 will get lost.

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #226 (with tests included)
This should help the codebase to achieve Python 3 compatibility.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Adds `from __future__ import absolute_import` and .imports within a module
- Used isort to sort imports
- Remove unused read_in()
- Remove unused imports
- Added `<search engine name> parsed: ` to the output to aid testing #271 -like issues.
- Added two test to app/test_server.py to ensure we do not have regressions
- Some code was processed by yapf to improve #265

### CODE REVIEW

**Comment by bhaveshAn** [comment]
Please provide heroku deployment for this PR to be reviewed. Thanks !

**Comment by cclauss** [comment]
I used Bluemix, not Heroku but #270

**Comment by bhaveshAn** [comment]
Heroku will not fail. Try heroku easy and free.

**Comment by cclauss** [comment]
https://scrapers-use-absolute-imports.herokuapp.com/

**Comment by cclauss** [comment]
Travis refuses to engage

**Comment by cclauss** [comment]
@niranjan94 This was the PR where Travis refused to engage.

**Comment by niranjan94** [comment]
@cclauss looks like travis had some issues on their side. That coincides with the day this PR was created. Could be related. https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Pull request closed without merging**
