### PR TITLE
 Lookup scrapers by name, not by initial

### LINKED ISSUE #226: Scrapers should implement absolute_import
The current scrapers will not work on Python 3 because they do relative importing.  The problem is shown here: https://travis-ci.org/fossasia/query-server/jobs/282968780#L558

The solution is to:
1. from __future__ import absolute_import
2. from .generalized import Scraper  # add the dot (.)
(See https://github.com/fossasia/query-server/pull/225/files#diff-ae74241666286cc647595b08d2de8ac2 for an example)

Without item 2 above, Python 3 will get lost.

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
@bhaveshAn Your thoughts please?

**Comment by niranjan94** [comment]
@cclauss please do not make multiple PRs for the same issue. Always update your existing PR

**Comment by cclauss** [comment]
This perfect PR policy is killing me.

See the glitter chat.  These changes are actually fixing issues but when I use command line git the Travis does not engage.  When I do web-based PRs, any simple oversight becomes a do over.  When I do over, I get grief for closing issues and opening new ones.

**Comment by niranjan94** [comment]
@cclauss I don't see what the issue here is ... 

From what I can see in this PR, travis has built every commit. (You can see the cross/tick symbol next to each commit). Travis always builds on each commit being pushed to the PR branch. Travis wouldn't care if it is from the Web UI or the CLI. 

So please, I suggest you learn more about git. It might be a mistake on your side. Maybe you don't push correctly. Or maybe you don't commit. I don't know exactly what is happening on your side. But as long as you push a commit, travis _will_ build it. 

So, closing PRs and opening new ones is _not_ the right solution for this.

**Pull request closed without merging**
