### PR TITLE
Fixes #453

### LINKED ISSUE #453: typo in local installation guide
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

In the local installation guide
screenshot from 2018-01-21 14-15-05

**Expected behavior:**

It should be `sudo service mongodb start`

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by datboiee**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x]  I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by cclauss** [comment]
Also the title of this PR forces the reader to look up another issue.  Please describe the issue in the title to speed up the review process.

**Comment by datboiee** [comment]
@ParthS007 I will not. lul go die

**Comment by datboiee** [comment]
@ParthS007 LOL open source

**Comment by ParthS007** [comment]
@datboiee Please follow best practices and don't use irrelevant words here 👍

**Comment by datboiee** [comment]
@ParthS007 im sorry

**Comment by vaibhavsingh97** [comment]
@datboiee Update please

**Comment by duttaditya18** [comment]
@vaibhavsingh97 I don't think @datboiee would follow up. This is a very small change and can be done by anyone. I think this PR must be closed.

**Comment by vaibhavsingh97** [comment]
Closing since no activity. Please free to request to reopen. 😄

**Pull request closed without merging**
