### PR TITLE
Implement absolute_import in Scrapers

### LINKED ISSUE #226: Scrapers should implement absolute_import
The current scrapers will not work on Python 3 because they do relative importing.  The problem is shown here: https://travis-ci.org/fossasia/query-server/jobs/282968780#L558

The solution is to:
1. from __future__ import absolute_import
2. from .generalized import Scraper  # add the dot (.)
(See https://github.com/fossasia/query-server/pull/225/files#diff-ae74241666286cc647595b08d2de8ac2 for an example)

Without item 2 above, Python 3 will get lost.

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #226

### CODE REVIEW

**Comment by cclauss** [comment]
@bhaveshAn Do you have Python 3 on your machine?  Would you be willing to run the current master branch and verify #226 and then test this PR and let me know how things work (or don't work)?

**Comment by bhaveshAn** [comment]
Yeah @cclauss following errror comes with python3
> Traceback (most recent call last):
  File "app/server.py", line 2, in <module>
    from scrapers import feedgen
  File "/home/bhavesh/Desktop/bhaveshAn/fossasia/query-server/master/app/scrapers/__init__.py", line 4, in <module>
    from google import Google
ImportError: No module named 'google'

**Comment by cclauss** [comment]
Perfect.  Then if you change
* from scrapers import feedgen   # -->
* from .scrapers import feedgen  # add the dot (.)

**Comment by cclauss** [comment]
Closed in favor of the more complete #235

**Pull request closed without merging**
