### PR TITLE
Added Search Frontend and Database

### LINKED ISSUE #21: Add a Graphical User Interface
The server is a command line tool currently. Add a GUI so that when deploying this server as a service, we can have a landing/home page similar to the one at https://loklak.org/ or http://api.asksusi.com/ .

### PR DESCRIPTION
**Pull request by enigmaeth**
This resolves #21 and #22.  
The server now uses a MongoDB database to store the query strings and search results.

### CODE REVIEW

**Comment by enigmaeth** [comment]
@niranjan94 Please review this PR. I wrote this query-server initially when it used file based storage. I have changed that to a MongoDB database. I have also added a search frontend. This will make the query-server deployable. We can have a central database hosted somewhere and connect the instances of the server( console-based or graphical interface) to that. 

This is in response to this issue here : 
https://github.com/fossasia/open-event-orga-server/issues/2675

**Comment by enigmaeth** [comment]
Take a look at this page:
screenshot_20170301_160233-min

This page will be the landing page of the hosted server. The UI can be certainly improved if we would want to.

**Comment by enigmaeth** [comment]
@niranjan94 Once this gets merged, I can start working on deploying the server. (https://github.com/fossasia/query-server/issues/10)
I will add docker file to make this docker deployable. We can have a docker image.

**Comment by enigmaeth** [comment]
We can do a test deployment. I'll set it up and let you know. 
And fixing the bootstrap thing right away.
Thanks.

**Comment by enigmaeth** [comment]
@niranjan94  
Have a look at : https://75a66df2.ngrok.io/

**Comment by enigmaeth** [comment]
Thanks. We host a central server and connect instances. I will write API endpoints for accessing data directly from the DB. 
We can open issues for more enhancements. I believe we definitely have to improve on the UI.

**Comment by enigmaeth** [comment]
I think for the last part, we can create buttons for the search engines which will reduce syntax errors.

**Comment by niranjan94** [comment]
Why should the API endpoints return stale data from the database? AFAIK, the query server should scrape and give the current fresh data as and when an API request is performed. 

And we should try to keep query server with as less overhead as possible since open event (and probably more future projects might be using it)... So I'd like to know what exactly is the purpose of storing the results in a database? We need the results to be fresh and not stale right. So storing it in a database seems like something we don't need to do.

@mariobehling need your opinion on this please...

**Comment by niranjan94** [comment]
Looks good. Merging now. We can come to a conclusion about the database later and make necessary changes. 

@enigmaeth please add a docker file and a heroku deployment for this repository.

**Comment by enigmaeth** [comment]
Yeah..sure!

**Pull request merged**
