### PR TITLE
Added GUI, Replaced File Storage by MongoDB

### PR DESCRIPTION
**Pull request by enigmaeth**
Added a graphical interface. 
Added MongoDB database.
This will help in scaling this particular service and writing API endpoints for accessing and manipulating data stored, also enabling to add Machine Learning/Big Data capabilities easily.

### CODE REVIEW

**Comment by mariobehling** [comment]
@enigmaeth Thank you for joining!

Unfortunately I am unclear about a number of changes. There are many different items addressed here. You have not opened an issue on the tracker and it was not therefore possible to discuss each change. You are now submitting a PR for a number of changes, that are difficult to review quickly.

Please open an issue for each major change and get the feedback of others. Please make a PR for each feature and match it with an issue like "Resolves: #issuenumberhere".

This will make it easier for reviewers and help everyone to stay on board. Thank you.

**Comment by enigmaeth** [comment]
@mariobehling Thanks for the review. I'll open new issues accordingly.  
The server's initial code was written by me. I upgraded some parts of it. 

I'll group the commits in issues as possible. Hope to discuss and get feedback there!

**Comment by enigmaeth** [comment]
@mariobehling 
Closing this pull request in favor of issue-specific pull requests.

**Comment by enigmaeth** [comment]
resolves#21 
resolves#22

**Comment by enigmaeth** [comment]
resolves #21 
resolves #22

**Comment by Abhi2424shek** [comment]
@enigmaeth next time open a pr for an issue for easy reviewing and this time pls squash the changes into one, one commit per PR is the fossasia standard. Happy coding :)

**Comment by enigmaeth** [comment]
Closing this for another PR #23 .

**Pull request closed without merging**
