### PR TITLE
Add condition to avoid infinite loop for ask.com.

### LINKED ISSUE #258: Ask search engine is crashing the web app
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Type any query let us say fossasia and choose count to 100 or 80+ and then you will notice that the web app will crash and then it will no longer work. It is happening because the result keeps on going and achieve infinite loop.

When ask.com gets to https://www.ask.com/web?q=fossasia&page=7 then at page 7 you will get no result so with no result nothing will append and it keeps on going to 8, 9, 10 with no result and then it becomes an infinite loop. It cannot be fixed except we can give exception to this search engine by showing or indicating an error message.
**Expected behavior:**

It should give proper 100 results

screenshot from 2017-10-20 11-55-17
screenshot from 2017-10-20 11-54-48

### PR DESCRIPTION
**Pull request by rupav**
Fixes #258 

#### Checklist

- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x] My branch is up-to-date with the Upstream `master` branch.
- [ x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- If page is empty with results, then ask.py scraper' parseResponse will return none.

- Then after receiving through generalized.py' search function in newResults, It will check for 'None' condition. If true, it will break out of otherwise infinite loop. 

I used following script to test the response, which was working fine if such case encountered.

On 7th page:

### CODE REVIEW

**Comment by rupav** [comment]
@shashank-sharma please review :).

**Comment by shashank-sharma** [comment]
Hi, Good going
Try to fix some error generating from travis-ci. Besides that I can see that it is not going in infinite loop which is great. But for different parameters I am getting different results, can you explain why ?

http://0.0.0.0:7001/api/v1/search/ask?query=fossasia&format=json&num=50 
Giving: 50 results which is great
http://0.0.0.0:7001/api/v1/search/ask?query=fossasia&format=json&num=60
Giving: 45 results
http://0.0.0.0:7001/api/v1/search/ask?query=fossasia&format=json&num=80
Giving: 36 results

**Comment by rupav** [comment]
@shashank-sharma I cant open your provided links (I think different outputs can only be due to ask.com, isnt it?) , I have corrected travis errors. But what is this error showing up: "missing whitespace after ':'". Can you help me with this and indentation error please . Thanks.

**Comment by shashank-sharma** [comment]
Hey @rupav 
As per what I understand your indentation on line 23 of ask.py is not proper. I cloned your repository and viewed this file.
See this image and see the error. Try fixing this and you will be able to clear few or all errors.

screenshot from 2017-10-24 19-32-03

**Comment by rupav** [comment]
@shashank-sharma I had to clean everything from my forked repo too, which eventually closed this PR. Sending a new PR.

**Pull request closed without merging**
