### PR TITLE
gigablast support added

### PR DESCRIPTION
**Pull request by starlord1311**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-made a new pr. but the icon for gigablast still cant be seen. otherwise the server is working properly locally
-

### CODE REVIEW

**Comment by starlord1311** [comment]
@bhaveshAn @raju249 please check

**Comment by bhaveshAn** [comment]
Resolve conflicts and Please provide heroku deployment

**Comment by starlord1311** [comment]
@bhaveshAn can you please tell what the conflicts are. i am not getting it.

**Comment by raju249** [comment]
Follow these steps @starlord1311 
Do `git fetch upstream` (Upstream being remote pointing to this repo)
Then merge the `master` branch using `git merge upstream/master`
then do a git push

**Comment by starlord1311** [comment]
thanks @raju249

**Comment by starlord1311** [comment]
@raju249 can you help with heroku deployment?

**Comment by starlord1311** [comment]
i have windows

**Comment by raju249** [comment]
Sure @starlord1311 
Ping me on gitter, or else the issue page may get long to scroll with comments :smi

**Pull request closed without merging**
