### PR TITLE
Implemented Counted Results for ASK.com

### PR DESCRIPTION
**Pull request by gabru-md**
Implemented the count feature for ask module for query server.
As discussed It provide with the maximum possible results for the given query.
Tested and works.

Fixes : https://github.com/fossasia/query-server/issues/188

### CODE REVIEW

**Comment by gabru-md** [comment]
Screen Shots of the following changes showing the scrapper.py generating 10 and 20 results

10res

20res

Please Review : @nikhilrayaprolu @vaibhavsingh97 @mariobehling :smile:

**Comment by gabru-md** [comment]
@mariobehling please review.

**Comment by AnshulMalik** [comment]
Travis is failing @gabru-md, can you please recheck?

**Comment by gabru-md** [comment]
@AnshulMalik the build isn't failing on my files.
It is failing on `scrapper/ask.py` and it will be solved by PR #191 
Cheers

**Comment by AnshulMalik** [comment]
Ok. Looks good to me

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by gabru-md** [comment]
I guess this is solved in #191 and u can thus clos this pr.

**Pull request closed without merging**
