### PR TITLE
Added Dailymotion support

### LINKED ISSUE #163: Adding Dailymotion support.
I am currently working on this issue

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #163 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Dailymotion

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
@bhaveshAn Please review

**Comment by bhaveshAn** [comment]
@jajodiaraghav Please provide heroku deployment for this as it would be easy to review then :+1:

**Comment by jajodiaraghav** [comment]
@bhaveshAn There you go: https://query-server-test.herokuapp.com/

Please review

**Comment by bhaveshAn** [comment]
@jajodiaraghav Heroku app coming with Application error.
Also, even after approval, not sure if it can be added, as earlier there was someone who wants to add medium support but since Medium isn't a search engine (Medium is an online publishing platform) , so it was not added even after PR approval. So same can be in the case of Dailymotion as (Dailymotion is a video-sharing website) and not search engine.

**Comment by jajodiaraghav** [comment]
@bhaveshAn The link works perfectly fine for me. Also, In case there was no plan for adding Dailymotion support, the maintainers should've closed the issue. Nobody asked me to hold when I claimed the issue. This is not the right way!

**Comment by jajodiaraghav** [comment]
@bhaveshAn The search engine argument holds for Quora and Youtube as well. I can see both the apps integrated with query-server

**Comment by bhaveshAn** [comment]
> The link works perfectly fine for me.

screenshot from 2017-11-22 23-58-48

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Are you still facing Application Error? Can I merge this?

**Comment by jajodiaraghav** [comment]
I think the issue was with Heroku (not sure)
@vaibhavsingh97 I have updated the branch

**Comment by jajodiaraghav** [comment]
Can we please merge this?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I am waiting for confirmation from @bhaveshAn

**Comment by ParthS007** [comment]
@vaibhavsingh97 I think we should also wait for @mariobehling

**Comment by bhaveshAn** [comment]
@vaibhavsingh97 I am still getting application error.

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Just checked and now I am getting Application Error too, but it's a strage behaviour as previously i checked and it's working perfectly.
Cc: @jajodiaraghav

**Comment by jajodiaraghav** [comment]
I just checked the heroku logs, and could not find any error or warning logged in it. The issue is with Heroku.

**Comment by jajodiaraghav** [comment]
Can we please merge this?

**Comment by raju249** [comment]
@jajodiaraghav Please merge the latest code from master to your branch.

**Comment by jajodiaraghav** [comment]
@raju249 Please merge

**Comment by raju249** [comment]
@jajodiaraghav 
I don't have the merge rights. So please wait for the maintainers to respond.
Also LGTM 👍 
Thanks

**Comment by realslimshanky** [comment]
@jajodiaraghav looks like your PR is out-of-date. Kindly rebase it with the master by taking a pull from this repo's master branch.

**Comment by jajodiaraghav** [comment]
@realslimshanky This PR has remained open for far too long and ins't been merge yet even though it is perfectly fine. I have already updated it twice. Do you have merge rights to this repo?

**Comment by realslimshanky** [comment]
@jajodiaraghav I don't have merge right. Please wait for maintainer's review.

**Pull request merged**
