### PR TITLE
remove inline css

### LINKED ISSUE #492: Remove inline css
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Inline css.
**Expected behavior:**

seperate css file.

**I am working on it**.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #492 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [x ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Inline css is not a good practice, hence incorporated the changes in styles.css
-  https://aqueous-refuge-13068.herokuapp.com/

### CODE REVIEW

**Comment by rupav** [comment]
@vaibhavsingh97 please review.

**Comment by rupav** [comment]
@ParthS007 squashed.

**Comment by rupav** [comment]
Ok @bhaveshAn , will rectify this.But will it not only override those bootstrap properties that are changed by my code?

**Comment by vaibhavsingh97** [comment]
@rupav Yes, Please don't modify Bootstrap classes. Please update the PR

**Comment by bhaveshAn** [comment]
> will rectify this.But will it not only override those bootstrap properties that are changed by my code?

As a result. They will modify the bootstrap classes which ever you are modifying and will affect others divs too which doesn't require modification.

**Comment by rupav** [comment]
@bhaveshAn rectified now. please review. @vaibhavsingh97 
PS: @bhaveshAn  I kept in mind about other divs earlier too while making the changes, only modifying those bootstrap classes' css which were used once in index.html

**Comment by rupav** [comment]
Updated heroku link too, so same as in the description.

**Comment by bhaveshAn** [comment]
>  I kept in mind about other divs earlier too while making the changes, only modifying those bootstrap classes' css which were used once in index.html

Thats not a good practice. My reason was to explains its effect. Although you are only supposed to make new classes and write their css. You don't have to modify the css of any of the pre-defined bootstrap class even if it is used once.
Making user-defined css style classes and writing its css is the best and only practice which should be followed.
Please do that !!

**Comment by rupav** [comment]
I have done that @bhaveshAn . I understood your suggestions earlier 😃. Changed to user defined classes. You can review, see the updated PR.

**Comment by rupav** [comment]
@vaibhavsingh97 please review

**Comment by realslimshanky** [comment]
@rupav Please resolve conflicts.

**Pull request merged**
