### PR TITLE
fix small_test()

### LINKED ISSUE #404: small_test() is broken: search() is missing a parameter
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

small_test() at https://github.com/fossasia/query-server/blob/master/app/scrapers/__init__.py#L34-L35 will raise an exception.

**Expected behavior:**

small_test() works as expected

**Steps to reproduce:**
Call small_test()

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #404 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- fix small_test() to align with https://github.com/fossasia/query-server/blob/master/app/scrapers/generalized.py#L37

### CODE REVIEW

**Comment by cclauss** [comment]
@vaibhavsingh97 Is something more needed on this PR?

**Comment by vaibhavsingh97** [comment]
@cclauss Please follow best practices, Please open issue and then send PR. Rest looks good

**Comment by cclauss** [comment]
Done.

**Comment by cclauss** [comment]
@dgarvit Please review this proposed change.

**Pull request merged**
