### PR TITLE
Fixes #411 Remove repeated auto-deployment buttons of Heroku and Docker

### LINKED ISSUE #411: Remove repeated auto-deployment buttons of Heroku and Docker
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently, there are repeated auto-deployments buttons in README.md
**Expected behavior:**

Removing, these auto-deployment buttons which came more than once in README.md
**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #411 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Removed repeated auto-deployment buttons of Heroku and Docker from README.md

@vaibhavsingh97 @gabru-md Please review

### CODE REVIEW

**Comment by ParthS007** [comment]
As this is a **beginner** issue and It should be only solved by **beginners** hence closing it . Please refer to #415 and add more such type of documentation and code refactor issue there.

**Comment by AnshulMalik** [comment]
That's insane @ParthS007 :P

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Any reason to open it again?

**Comment by bhaveshAn** [comment]
@ParthS007 
As the PR has been made, so I will add documentation and code refactor issue (OTHER THAN THIS) at #415 from now.
But, since this PR has been made, so this will be treated as it is. 
Also, please don't feel that you are the only Maintainer over here. Review of most of the Maintainers and Contributors are required at each PR, infact 2 reviews according to your statement https://github.com/fossasia/query-server/pull/392#issuecomment-352088491 (So Please follow best practices) :smile: . The best way would be to share your opinion, that's it, without closing the PR.

Suggestion from my side, if you could please give some update on #321 that would be much better. As you have claimed the issue since Nov 8, 2017, and no update has been given. Though now it looks like the self assigned the issue, since ages. So, now the time is to make new year resolution. :sweat_smile: 
Happy New year :fireworks:

**Comment by bhaveshAn** [comment]
@vaibhavsingh97 As the PR has been made so, it would be better to consider it as it is. 
Though if some other docs issue will be there I will add it to #415

**Comment by ParthS007** [comment]
Hi @bhaveshAn Happy New year 🎉 , 
The reason I closed this PR as you are an experienced developer and you should solve intermediate/advance PR. These type of issues can be solved by newcomers/ beginner. Moreover, I discussed this issue with @vaibhavsingh97 and he suggested me to close this PR since this can be solved by a beginner. Also, We are in a team in FOSSASIA so we should move collectively and I respect your viewpoint and I was busy with GCI evaluations so that's why #321 is missed but @vaibhavsingh97 is working on #321 and I will remove assigned label(Nice catch). 
Moreover, I tried to share my opinion in #358 also. I hope you understand, Please don't take it otherwise.
I take every day as a new day and every day I have some resolutions so new year resolutions are not required.

**Comment by bhaveshAn** [comment]
@ParthS007 
> The reason I closed this PR is as you are an experienced developer and you should solve intermediate/advance PR. These type of issues can be solved by newcomers/ beginner. 

No worries. But if someone has fixed that. So it doesn't require to be closed and opened same by other dev. That's what I mean. 

> I take every day as a new day and every day I have some resolutions so new year resolutions are not required.

Nice to know that :+1:

**Comment by vaibhavsingh97** [comment]
Closing wrt: https://github.com/fossasia/query-server/pull/412#issuecomment-354671655

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Sorry, But let beginner solve this. You can claim any other issue. Thanks

**Pull request closed without merging**
