### PR TITLE
Fix Google scraping method

### PR DESCRIPTION
**Pull request by shashank-sharma**
Fixed: #166 
According to the previous code at first it scrapes all the link from there and if it is not equal to the given length it gets incremented by 10 and search again. But we were getting only 9 results rather than 10 due to which it returns nothing and for loop exits.

Issues: When page fetches less than 10 result it breaks. Now its working fine

screenshot from 2017-09-23 13-10-01

screenshot from 2017-09-23 13-10-46

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@shashank-sharma can you please add Fixes: #166 in your description

**Comment by AnshulMalik** [comment]
Can you provide a working demo link please?

**Comment by shashank-sharma** [comment]
@AnshulMalik Hi, is it okay if you can check this working demo by api ?

Link: http://test-query-server.herokuapp.com/api/v1/search/google?query=paradise&format=json&num=10

Actually the homepage is looking bad maybe because of bower install command is not executed in heroku server I guess. But still that link can show you if it is working fine or not.

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
