### PR TITLE
Lookup scrapers by name, not by initial

### LINKED ISSUE #226: Scrapers should implement absolute_import
The current scrapers will not work on Python 3 because they do relative importing.  The problem is shown here: https://travis-ci.org/fossasia/query-server/jobs/282968780#L558

The solution is to:
1. from __future__ import absolute_import
2. from .generalized import Scraper  # add the dot (.)
(See https://github.com/fossasia/query-server/pull/225/files#diff-ae74241666286cc647595b08d2de8ac2 for an example)

Without item 2 above, Python 3 will get lost.

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #226 Replaces #227 Enables #225 Helps with issues in #229 , #230 , #231

#### Checklist 

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- #226 Use absolute importing for Python 3 and 2
- https://github.com/fossasia/query-server/pull/230#issuecomment-334662376 Lookup scrapers by name instead of by a single letter.
- Reduce repetitive scraper list + scraper dict down to a single scraper dict (prep for #233)

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@cclauss Please check on cadacy :)

**Comment by gabru-md** [comment]
@cclauss there are three commits for this PR.
Please Squash them.

**Comment by cclauss** [comment]
@gabru-md What commands do I type to do that?

**Comment by cclauss** [comment]
If someone could create a YouTube proof of how to squash three commits into a single commit, that would be a huge help to me.

**Comment by gabru-md** [comment]
@cclauss listen this is what you have to do

Here you have 3 commits that you have to squash into one. So follow these steps and let me know
1. Go to you local and open terminal. Type
```sh
$ git rebase -i HEAD~3
```
2. Now replace `pick` with `s` for two of your commits. Press Ctrl+X and save the file.
3. Now you will have to change the commit message , change it to whatever you like is relevant. Save it.
4. Push your changes to your branch
```sh
$ git push origin development(or whatever branch you have it)
```
If you have any trouble try 
```sh
$ git push -f origin development(or whatever branch you have it)
```

**Comment by niranjan94** [comment]
@cclauss any update on this PR ? been open for long

**Comment by cclauss** [comment]
@niranjan94 Sorry...  Outside pressures have kept me from focusing.  When making changes to 9 files at once, testing is important so the lack of pytest continues to hurt us.  Also, as you can see my git skills are abysmal which compounds the struggle.  However, I will get back to this one because I do believe that it helps us to remove complexity.

**Comment by cclauss** [comment]
I need to redo this PR given all the codebase changes in the interim.

**Pull request closed without merging**
