### PR TITLE
Fix Heroku Deployment

### LINKED ISSUE #184: Application error on website
I see this error when I open the website https://query-server.herokuapp.com/. 

screen shot 2017-09-24 at 7 59 38 pm

### PR DESCRIPTION
**Pull request by S2606**
Fixes #184

### CODE REVIEW

**Comment by S2606** [comment]
@AnshulMalik @gabru-md Please review

**Comment by AnshulMalik** [comment]
I can't deploy it on heroku, says:

The content of app.json is not valid; please see app.json Schema for more information.

**Comment by gabru-md** [comment]
Great! Why not just squash them ?
:+1:

**Comment by shashank-sharma** [comment]
@AnshulMalik Look for every PR the travis is breaking with same error:
 F821 undefined name 'get_ask_page'

**Comment by AnshulMalik** [comment]
Yes @shashank-sharma I can track the error back to https://github.com/fossasia/query-server/pull/182

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
