### PR TITLE
Add yaydoc configuration file for docs generation

### PR DESCRIPTION
**Pull request by imujjwal96**
Here are the generated docs: http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/85fec170-7409-4ba6-9c58-a0ae3c9436ab_preview/

Fixes: #70

### CODE REVIEW

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y  Please review.

**Comment by pri22296** [comment]
@imujjwal96 Any reason why clicking on a link in the table of contents section in the start page doesn't scrolls down to that section?

**Comment by imujjwal96** [comment]
@pri22296 seems to be an issue of markdown conversion
`- [Error Codes](#error-codes)` is converted to `href="#error-codes.html"`

**Comment by pri22296** [comment]
Ok, This seems to be an issue related to how we preprocess markdown links before conversion. Please create an issue for this. This shouldn't block this PR though.

**Comment by imujjwal96** [comment]
@pri22296 I guess you'd be the best person to raise the issue. You've understood the problem and will be able to explain it unlike mt :D

**Comment by imujjwal96** [comment]
@pri22296 had to update the theme name

**Pull request merged**
