### PR TITLE
Fixes #57 implemented teaser text for all search providers

### LINKED ISSUE #57: Improve scraper to provide teaser text
Currently the teaser text is being shown only for BING on query-server, but it isn't being shown for other search engines. Please improve the scraper to provide teaser text for Google and other search engines as well.

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
fixes #57 implemented teaser text for all search providers.
image

@mariobehling please review

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@enigmaeth please review.

**Comment by enigmaeth** [comment]
Please rebase it, elsewise looks good.

**Comment by nikhilrayaprolu** [comment]
@enigmaeth rebased.

**Comment by nikhilrayaprolu** [comment]
@enigmaeth can you also look at other pull requests #73 #68 #67

**Comment by hpdang** [comment]
Good job!

**Pull request merged**
