### PR TITLE
Added houndCI config file

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes: #174

Changes:

    Added config file for integartion of HoundCI

@mariobehling Please enable HoundCI Integration for this project

### CODE REVIEW

**Comment by cclauss** [comment]
I do not believe that this PR adds anything over the functionality that we already have in Travis.  See comments in #174.

Also a separate .flake8.ini merely moves configuration details away from where the flake8 command that is being run.  I would rather see `flake8 --exclude=.git,__pycache__ --max-line-length=120` rather than putting these details elsewhere.

This would cause us to have hunt elsewhere for the configuration to understand execution properties of the command that is in front of us has been doing.  In .travis.yml we directly control how flake8 works and that gives us the flexibility to execute two very different passes with the same tool.

**Comment by vaibhavsingh97** [comment]
@cclauss So as an beginner/newcomer if someone send new PR then that are not so familiar with Travis CI so what Hound CI does is that it directly review and tell that which lines have violations. So beginners can fix these issues. also, it will be better that PR goes through 2  CI's. What's your opinion on this?

**Comment by cclauss** [comment]
If there is a significant UI difference that helps the submitter then I am all for that (as long as it does not make a second commit which would violate the perfect PR policy).

**Comment by cclauss** [comment]
I tried hound on one of my repos and now I see what you mean.  I like it.

**Comment by vaibhavsingh97** [comment]
@cclauss I understand your concern but as a first timer we should give them one chance we can improve somebody at on go. But we will tell them to squash commits with the link of best practices of FOSSASIA. And I don't think we need any extra documentation for hound CI

**Comment by cclauss** [comment]
OK.  I agree.

**Comment by vaibhavsingh97** [comment]
@AnshulMalik Please review 😅

**Comment by AnshulMalik** [comment]
I haven't used Hound CI. In my opinion, flake does the job, And I am planning to incorporate flake into git precommit hook so that style guidelines are always met.

Can you tell me the pros of using hound ci ?

**Comment by vaibhavsingh97** [comment]
@AnshulMalik Hound reviews your code when a pull request is opened or updated. If Hound finds any style violations in the modified code it will comment on the appropriate line. It will be easier for the beginners to fix the issue and makes the life easier for reviewer and if we add flake8 in travis build than PR will fail due to violations in the PR so beginners will find difficult to debug and fix the issue

**Comment by AnshulMalik** [comment]
We can give this a try then

**Comment by AnshulMalik** [comment]
Also, can you please add a newline at the end of these files ?

**Comment by vaibhavsingh97** [comment]
Closing this PR since I messed up with my branch 😅

**Pull request closed without merging**
