### PR TITLE
max-line-length to 150 in travis

### LINKED ISSUE #252: Increase --max-line-length in travis.yml
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
Apologies, earlier changed the `--max-line-length` for HoundCI and not for Travis CI. This issue is in regards of same in Travis.
 
**Current behavior:**

Currently, --max-line-length = 85 in .travis.yml is responsible for build failing at #240 
**Expected behavior:**

Changing --max-line-length = 85 to --max-line-length = 150 in .travis.yml will pass the build and in future too.
**Steps to reproduce:**

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #252 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Increase --max-line-length in travis.yml

### CODE REVIEW

**Comment by cclauss** [comment]
Reading code in the GitHub web UI is a common practice.  Code wider than 127 characters requires scrolling left and right in that UI which is highly sub-optimal for the reader.

I would rather see you wrap these lines or that you tell flake8 to excludes the file app/templates/index.html or the directory app/templates/  See the flake8 docs on how to do this.

**Comment by bhaveshAn** [comment]
@cclauss Please refer to comment https://github.com/fossasia/query-server/pull/240#issuecomment-336542311

**Comment by cclauss** [comment]
Good.  So we can close this pull request because the fix is to wrap the line of Python?

**Comment by bhaveshAn** [comment]
Nope we have to add the search engines in that tuple that i mentioned in the server.py and since the line is too long and we can't split the lines as the lines can't be split inside parenthesis which is another violation of flake8 so need to do it at any cost to run more search engines. 
No need to close this PR.

**Comment by bhaveshAn** [comment]
@cclauss please approve

**Comment by cclauss** [comment]
```python
if engine not in ('google',
                  'bing',
                  'duckduckgo',
                  'yahoo',
                  'ask',
                  'yandex',
                  'lycos',
                  'exalead',
                  'teoma',
                  'cosiaE'):
    pass
```

is perfectly valid Python that flake8 will not complain about so I do not understand the need for long lines.  When in doubt run autopep8 on your code.

**Pull request closed without merging**
