### PR TITLE
Pep 8

### PR DESCRIPTION
**Pull request by newbazz**

### CODE REVIEW

**Comment by mariobehling** [comment]
@newbazz Thanks for joining development! It is difficult for us to understand what you are working on and what issue are you trying to solve. Please help us and first open issues, then match issues with PRs. Please follow best practices to make it easier for everyone to collaborate with you: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Please update your PR description and commit message. Cheers.

**Comment by newbazz** [comment]
image
This is my log and the latest commit before me is from Shashank sharma, same is the case with query-server master. What more commits do i need to rebase on?

**Comment by vaibhavsingh97** [comment]
@newbazz Thanks for your contribution. Can you please add description for this PR and as I can see that you had open this PR  to format the code according to the PEP8 standard. Please cover all the files and also we have one commit per PR policy so please adhere to that 😄

**Comment by cclauss** [comment]
@newbazz sense what you are trying to do but I think you would need to attack it with an automated tool like [autopep8](https://github.com/hhatto/autopep8) or yapf and then submit the entire thing in one single commit.  No mistakes allowed.  To do that you need to have good skills with git on the command line.

**Comment by Pk13055** [comment]
Please refer to #151. And next time onwards, do take a look at the existing pulls before creating a new one!

**Comment by newbazz** [comment]
Since #151 is already there i am closing this.

**Comment by cclauss** [comment]
Now that flake8 is set up in Travis, we get __a full listing of all PEP8 style violations__ (the Exxx errors): https://travis-ci.org/fossasia/query-server/jobs/279784188#L662  There is work to do here @newbazz so I hope that we can see some more PRs from you.  Thanks!

**Pull request closed without merging**
