### PR TITLE
Changes buttons CSS and adds FB meta tags

### PR DESCRIPTION
**Pull request by sinAshish**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- I have added necessary Facebook meta tags for OG.
- I have changed the CSS of buttons.
- I have made Twitter share button to open on a new page.

### CODE REVIEW

**Comment by sinAshish** [comment]
Follow button cahnged, to make the page look good.
query1
The Outline hover buttons.
query2
Earlier the tweet share used to open on the same page, so changed that too.
query3

**Comment by ParthS007** [comment]
@sinAshish Screenshots are looking good but it will be great if you provide the link Heroku deployment of this PR. Thanks 👍

**Comment by sinAshish** [comment]
I had never deployed on [Heroku](https://ashish-query.herokuapp.com/) before, and the result is quite shocking to me. It is not as what was on my localhost. Can you tell me what is the problem?

**Comment by bhaveshAn** [comment]
Please follow the guide at `docs/installation/heroku.md`

**Comment by sinAshish** [comment]
Thanks @bhaveshAn . The [link](https://stark-anchorage-48083.herokuapp.com/) looks good now.

**Pull request merged**
