### PR TITLE
changesmade to server.py to prevent XML attacks issue #346

### LINKED ISSUE #346: xml.dom.minidom.parseString to parse untrusted XML is vulnerable to attack
https://www.codacy.com/app/fossasia/query-server/issues says: app/server.py
Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function.

Line 71: xmlfeed = parseString(

**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by starlord1311**
Fixes #346 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-xml.dom.minidom changed to defusedxml.minidom and defusedxml added to requirements.txt
-

### CODE REVIEW

**Comment by starlord1311** [comment]
@cclauss shouldnt pip install defusedxml be added to local.md? because i guess it isnt installed already.

**Comment by cclauss** [comment]
Nice!  Local.md recommends: __pip install -r requirements.txt__ so defusedxml will get installed in that operation.  Thanks so much for making us all safer!

**Comment by starlord1311** [comment]
@cclauss okay thanks. no changes needed right?

**Comment by cclauss** [comment]
Please edit your description text above, to read: __fixes: #346__ so that reviewers will have more context.

**Comment by raju249** [comment]
@starlord1311 Please update this branch with master of main repo.
Thanks

**Comment by starlord1311** [comment]
there is only one commit shown when i am doing git rebase -i master

**Comment by cclauss** [comment]
* git fetch upstream
* git rebase upstream/master
* git rebase -i master
* git push --force origin defusedxml

**Comment by starlord1311** [comment]
@cclauss  idk why the other commits by @bhaveshAn are also coming as well. are they supposed to?

**Comment by cclauss** [comment]
It still looks good to me. And it has two positive reviews.

**Comment by cclauss** [comment]
@starlord1311 I think at this point, you need to close this PR and create a new one.  Your original fix was just in two files but now this PR touches 21 files.

**Comment by rupav** [comment]
@starlord1311 I think you can rebase this way:
1). `git log --graph`. See your commit id (the one you made changes to).
2). then `git reset --hard <commit_id>`
3). now you will be back to square one (i.e. not rebased yet).
4). now checkout to your master branch ` git checkout master`
5). now rebase, i.e. `git pull origin master master`
6). now you need to add the branching point to the new Head. 

I haven't come across such case so I haven't tried 6th point. But that's should be the preferred workflow.
@cclauss what do you think?

**Comment by cclauss** [comment]
Nice!  I was good up until step 6 but then I got lost.  How do I do step 6?

**Comment by rupav** [comment]
@cclauss  in step 1 , last commit (i.e. the one that starlord1311 committed) 
In between step 5 and 6, I am not sure exactly, but basically we want to merge the branch to the new HEAD,
so `git merge master <branch_name>` should complete step 6.

**Comment by starlord1311** [comment]
@cclauss am i supposed to create a new pr?

**Comment by rupav** [comment]
@starlord1311 what was happening following the steps I suggested?

**Comment by cclauss** [comment]
We are trying to go them (not so successfully) on gitter chat.

**Comment by cclauss** [comment]
Magic!!

**Comment by dgarvit** [comment]
This is causing #388

**Pull request merged**
