### PR TITLE
add .dockerignore and .editorconfig

### LINKED ISSUE #237: Add .editorconfig, .dockerignore and docs of installation and deployments
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

1. **`.editorconfig`** will provide:

    `charset and indent_size = 4`

2. **`.dockerignore`** will ignore `.gitignore` files while deployment

3. ***Docs of installation and deployments*** provides:

    Local Installation inside `/docs/installation/local.md`
    Deployment on Docker inside `/docs/installation/docker.md`
    Deployment on Heroku inside `/docs/installation/heroku.md`

**Steps to reproduce:**

**Would you like to work on this issue**
Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #237 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Add .editorconfig and .dockerignore 
- Add separate docs of installation and deployments inside `/docs/installation/`

@mariobehling please review.

### CODE REVIEW

**Comment by bhaveshAn** [comment]
Yes, they both are in `README` and respectively at `heroku.md` and `docker.md` as well according to this PR.

**Comment by bhaveshAn** [comment]
@niranjan94 I have Fixed both issues separately. For #239 fixed at #243 . Please review both PRs again.

**Comment by bhaveshAn** [comment]
@niranjan94 please review. 
Commits can't be rebased further as the upstream commits will make mine.(if rebased more)

**Comment by vaibhavsingh97** [comment]
@bhaveshAn Please squash commits into one

**Comment by bhaveshAn** [comment]
@S2606 Thanks !
@vaibhavsingh97 Commits can't be rebased further as the upstream commits will make mine.(if rebased more)

**Comment by bhaveshAn** [comment]
@niranjan94 please review. Thanks

**Pull request merged**
