### PR TITLE
more informative tweet text

### LINKED ISSUE #330: Change of tweet message.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Right now, the tweet only consists of a couple of hashtags, with no message of any  other kind.
**Expected behavior:**

The tweet should be like _Hey, Check out this new search engine with which you search on multiple platforms all at the same time._  Followed by a couple of hashtags, so that the people who see the tweet get to know about Query Server.
**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by sinAshish**
Fixes #330 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- I have updated the tweet message, to make it more informative about the product.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by sinAshish** [comment]
Not showing any conflicts in mine.

**Comment by raju249** [comment]
Taken care in #363 
@ParthS007

**Comment by ParthS007** [comment]
closing with the reference to #363

**Pull request closed without merging**
